version: '3'
services:

  backend-api:
    build: ./backend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - backend-service  
      - frontend-service
    environment:
      - MONGO_DATABASE=bounty-hunters
      - MONGO_HOST=backend-db
      - MONGO_PORT=27017

      - JTW_SECRET=doutorequemtemdoutorado

  backend-db:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    volumes:
      - './temp/data:/data/db'
    networks:
      - backend-service  

networks: 
  backend-service:
  frontend-service: